Dockerfile
Makefile

Using the date in the tag wasn't a good idea and it only leads to a lot of different tag referencing the same docker image

Remove date from docker image tag

---

Dockerfile

Without it, weekly build 2.322 failed during packaging because the gpg command was not available on the agent.

fix: add gpg dependency in the Docker image

---

Dockerfile

Removed since `--no-install-recommends` has been added.

fix: add missing git dependency to the Docker image

---

Dockerfile

Removed since `--no-install-recommends` has been added.

fix: add missing openssl dependency to the Docker image

---

Dockerfile

WiP...
- Bump Maven to 3.8.4 (instead of ubuntu 18 default package)
- Bump JDK 8 to 11:
- Adoptium (instead of OpenJDK's Ubuntu 18 default)
- Pin version to 11.0.13+8
- Define the image as a Jenkins Inbound Agent capable image, to unlock the ability for single-container pod
- Retrieve the agent.jar and entrypoint shell script from the official jenkinsci/docker-inbound-agent repository
- Add dependencies required by other "side container" on jenkins-infra/release project:
- `az` CLI
- `jx-release-version` CLI
- `gh` CLI
- Chore: start adding labels with the installed tools and versions

fix: switch linux packaging to single-container JNLP

---

Dockerfile

I'd like to be able to run the unit tests for `jenkinsci/packaging` in `pytest` rather than `unittest`. The `pytest` test runner provides support for generating JUnit XML files, which can be used with the Jenkins JUnit plugin to provide a visual test result report in the Jenkins UI.
This PR adds the `python3-pytest` package, which I've tested in a local build and confirmed to be able to generate JUnit XML results in `jenkinsci/packaging`.
As a bonus, I'm also adding `python3-venv`. This isn't needed for what I'm doing, but it's a prerequisite for doing just about anything interesting with Python, so we might as well include it.

Install additional packages

---

Dockerfile

The 2.331 release failed with the following error:
```
+ jarsigner -verbose -verify -certs -strict /home/jenkins/agent/workspace/core_release_master/release/war/target/jenkins.war
utils/release.bash: line 476: jarsigner: command not found
```
We are missing https://github.com/docker-library/openjdk/blob/3ce4449d7f01afa6001a711e17cdd379b76848f8/8/jdk/bullseye/Dockerfile#L28 in this image.
This PR aims at fixing it by adding the whole default (JDK8) bin to the PATH.
Result is:
```shell
docker run --rm -ti --entrypoint bash <new image in this PR>
jenkins@6b9761c20cbb:/$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
jenkins@6b9761c20cbb:/$ 
jenkins@6b9761c20cbb:/$ which …
```

fix: add (default)jdk bin to the path

---

Dockerfile
macros.d/macros.systemd

Downstream of #28. Expanded from:
https://github.com/systemd/systemd/blob/main/src/rpm/macros.systemd.in
These macros are needed to build RPM packages that use `systemd`, but as far as I can tell they aren't packaged anywhere in Debian and Ubuntu. By including this in the base image, we can build RPMs that use `systemd` from Debian/Ubuntu.

Add systemd RPM macros

---

macros.d/macros.systemd

@ekohl points out in #29 and jenkinsci/packaging#266 that the macros added in #29 rely on systemd v250, which is quite new. This PR downgrades the macros to the ones from systemd v239, which should work on older Linux distribution versions.
I tested this by running the Molecule tests from jenkinsci/packaging#266 successfully.
CC @dduportal @ekohl @timja

Use older systemd RPM macros

---

macros.d/macros.javapackages-filesystem

These were removed from `rpm` in https://github.com/rpm-software-management/rpm/commit/a9199f17be42d22791caa33c1d79157b29b811d2
Fedora and OpenSUSE provide it to rpm specs via the `javapackages-tools` package which isn't packaged for ubuntu.
I've imported the relevant macro from Fedora: https://github.com/fedora-java/javapackages/blob/6.0.0/macros.d/macros.javapackages-filesystem
see https://github.com/jenkinsci/packaging/pull/317

Add Java packaging macros

---

Dockerfile

See failing tests in https://github.com/jenkinsci/packaging/pull/317

Add gnupg2 required for rpm signing on Ubuntu 22.04

---

Dockerfile

I couldn't build this image on my machine before so didn't actually test https://github.com/jenkins-infra/docker-packaging/pull/34
turns out it individually added the systemd macro
I've tested this locally
separate PR incoming for making this image portable across architectures

Copy all macros

---

Dockerfile

_Note 1: this removes java 8 from the packaging image_
_Note 2: this isn't fully arch independent as the Azure CLI doesn't publish an arm package, but it's not needed for the packaging part so contributors can test just fine, I've made it not fail the build now_
I've tested this locally and I can build packages just fine
I expect it to work just fine for releasing, we have a weekly this upcoming week we could test it on before LTS release.
Its important this image works on arm64 as any contributors on recent laptops won't be able to test packaging changes without it

Make architecture independent

---

Dockerfile

The goal of this PR is to allow later on to build an `aarch64` `docker` image so that we can build on Oracle `aarch64` free tier,  Amazon Graviton 3, and so on...
The first step (for me, correct me if I'm wrong) is to allow the build for several architectures thanks to `buildx`.
Before changing the `Makefile`, I think we should get rid of `docker` images that are not multi-arch.
We were grabbing `jx-release-version` from a `docker` image which unfortunately is not yet multi-arch.
Following advice from @lemeurherve, I replaced this `FROM` with a direct installation from the `github` release process to have `jx-release-version` available for this image (the tool is released for several architectures (`amd64`, `arm64`, `arm32`).
I gave a try at `docker buildx build` with several platforms. …

chore: retrieve jx-release-version from github instead of its docker image

---

cst.yml
updatecli/updatecli.d/jenkins-agent-version.yml

as per https://github.com/jenkins-infra/docker-packaging/issues/44#event-7066220391
PULL REQUESTS
=============
[Dry Run] A pull request with kind "github" and title "[updatecli] [jenkins-agent-version] Bump jenkins-agent version" is expected.
=============================
REPORTS:
⚠ JENKINS-AGENT-VERSION.YML:
Sources:
✔ [lastVersion] Get the latest jenkins-agent docker-inbound-agent version (kind: githubrelease)
Condition:
✔ [checkDockerImagePublished] Is latest dockerfile docker-inbound-agent image published? (kind: dockerimage)
✔ [testDockerfile] Does the Dockerfile have an ARG instruction which key is JENKINS_AGENT_VERSION? (kind: dockerfile)
Target:
⚠ [updateDockerfileVersion] Update the value of ARG JENKINS_AGENT_VERSION in the Dockerfile (kind: dockerfile)
Run Summary
=========== …

feat(updatecli): new manifest to keep updated the jenkins docker inbound agent

---

Dockerfile
cst.yml
updatecli/updatecli.d/jenkins-agent-version.yml

Related to https://github.com/jenkins-infra/helpdesk/issues/3072

breaking: switch to JDK17 for agent processes

---

Dockerfile
cst.yml

#74 switched the default JDK11 (from the Jenkins agent image) to JDK17.
But (at least for today) Jenkins is built with JDK11 v11.0.20 so we need to keep the same JDK for now.
This PR adds back the JDK11 by separating explicitly the JDK from agent and the JDK for building.
The JDK for the agent is NOT added as the default in `update-aleternatives` as the `JAVA_HOME` is used for the build JDK e.g. the 11: this is a breaking change.
Note:
- No `updatecli` manifest added in this PR (in a subsequent one).

feat! add temuring JDK11 11.0.20+8 as default JDK (breaking)

---

updatecli/updatecli.d/jenkins-agent-version.yml

This PR uses the agent repo as source reference instead of the inbound-agent repo, as this one has been integrated into the agent one.
Follow-up of:
- https://github.com/jenkinsci/docker-agent/issues/570
Ref:
- https://github.com/jenkinsci/docker-agent/issues/569#issuecomment-1890230875

chore(updatecli): use `agent` repo as source reference in the `inbound-agent` manifest

---

updatecli/updatecli.d/maven.yaml

Related to: https://github.com/jenkins-infra/helpdesk/issues/4110
Tried locally to update maven to latest release version(3.9.7)

chore(updatecli) Track Maven version.

---

cst.yml
updatecli/updatecli.d/jenkins-version.yaml
updatecli/updatecli.d/maven.yaml

This PR introduces 2 fixes for updatecli manifests:
- Fixup of https://github.com/jenkins-infra/docker-packaging/pull/113: I forgot about the test harnes (adding a target to update Maven version in it)
- Fix of the `jv` manifest by updating `updatecli` deprecated keywords

chore(updatecli) fixups for `jv` and Maven manifests

---

updatecli/updatecli.d/jdk-build.yml
updatecli/updatecli.d/jenkins-agent-version.yml
updatecli/updatecli.d/jenkins-version.yaml
updatecli/updatecli.d/maven.yaml
updatecli/values.yaml

This PR is a follow up of the work done in #111 and #115 by @jayfranco999 and I.
The goal is to cleanup the manifest to:
- Ensure Jenkins agent version is ready for upcoming JDK21 by using the same technique as we did in #115 
- Remove deprecated messages from `updatecli`
- Ensure homogeneity between manifests and stricter YAML syntax
- Help beginners by making relative path explicit

chore(updatecli) manifest cleanup to remove deprecated instructions and handle future JDK21 upgrades

---

README.adoc

Hyperlink previously pointed to the charts repository.

Use correct documentation hyperlink to release repository

---

Jenkinsfile_k8s

Reverts https://github.com/jenkins-infra/docker-packaging/pull/124 to help in https://github.com/jenkins-infra/docker-packaging/pull/133 to support Ubuntu 24.04 builds

chore: remove unneeded arm64 builds

---

updatecli/values.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4121
use updatecli to generate the new PR to upgrade from jdk17 to jdk21

chore(updatecli): change major jdk to 21

---

updatecli/updatecli.d/jdk-build.yml

following #173 it appear that we have some enhancement to apply to the updatecli manifest to keep tracking the jdk correctly within the CST file

chore(updatecli): enhance manifest for jdk update

---

Dockerfile
cst.yml
updatecli/updatecli.d/azcopy.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4696#issuecomment-3052689033
we need azcopy in this image to be used with the new private report monitoring system

feat: add azcopy in the image with the corresponding updatecli
